displayName=Ground Object Hider
author=Leo288,De0,umer-rs
description=Hides Ground Objects. A selector is used to choose objects to hide.
tags=external, objects, memory, usage, ground, decorations, performance
plugins=com.objecthider.ObjectHiderPlugin
